### ISSUE TITLE
PGO unable to create pvc on supplied storage class

### ISSUE THREAD

**Issue by ksingh7** [red-hat-data-services/jumpstart-library#12]
Even after specifically providing storage class, pgo create database yaml is not honouring that

![image](https://user-images.githubusercontent.com/9701902/115224473-8101a880-a12a-11eb-9ef8-d2725ffd54f4.png)

```
  PrimaryStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name:  pgdb
    size: 1G
    storageclass: "ocs-storagecluster-cephfs"
    storagetype: create
    supplementalgroups: ""
```
