### ISSUE TITLE
[Doc] Need to add instruction in Image Server section to create external RGW route

### ISSUE THREAD

**Issue by netzzer** [red-hat-data-services/jumpstart-library#71]
Currently OCS 4.7/4.8 does not automatically create an external route for RGW. This needs to be added as a manual step in the Image Server section if an external route to RGW is required to populate in image-server deployment as well as to push image files into the dataset-generator object bucket.

Example rgw_external_route.yaml.
```
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: s3-rgw
  namespace: openshift-storage
  labels:
    app: rook-ceph-rgw
    ceph_daemon_id: ocs-storagecluster-cephobjectstore
    ceph_daemon_type: rgw
    rgw: ocs-storagecluster-cephobjectstore
    rook_cluster: openshift-storage
    rook_object_store: ocs-storagecluster-cephobjectstore
spec:
  to:
    kind: Service
    name: rook-ceph-rgw-ocs-storagecluster-cephobjectstore
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
```
